### ==========================================
### 1. REGISTRAR USUARIO
### ==========================================
POST http://127.0.0.1:8000/registro/
Content-Type: application/json

{
  "email": "pepe7@gmail.com",
  "password": "000000"
}


### ==========================================
### 2. LOGIN (OBTENER TOKEN FIREBASE)
### ==========================================
POST http://127.0.0.1:8000/api/auth/login/
Content-Type: application/json

{
  "email": "pepe7@gmail.com",
  "password": "000000"
}


### ==========================================
### 3. CREAR CITA
### ==========================================
POST http://127.0.0.1:8000/citas/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY3VhcnRvLXRyaW1lc3RyZS1jcmlzdGlhbiIsImF1ZCI6ImN1YXJ0by10cmltZXN0cmUtY3Jpc3RpYW4iLCJhdXRoX3RpbWUiOjE3NzU2NjcwMzMsInVzZXJfaWQiOiJ5dE1oUWl4cGpMUVBpZGlJbFprUXFoOEsxaG0xIiwic3ViIjoieXRNaFFpeHBqTFFQaWRpSWxaa1FxaDhLMWhtMSIsImlhdCI6MTc3NTY2NzAzMywiZXhwIjoxNzc1NjcwNjMzLCJlbWFpbCI6InBlcGU3QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJwZXBlN0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.DUBpBPa8Tk1_Ttmmd9r5ZhPud7aiYQweObSKAPxZatL5kXTiVZVfpy58YNzwA7A-3Z2WHXx5hQVz-rkkqDs6DbR7_43C_zpvU3WIj_e8P-2u-3poS0VfdUb0Yz7QAsHPtANO4Fkoyniu6sA1fTREf4bpNGgPyD5WL3j-_LaRAXVK952PfVP8wrE8IC-JFoywFtoPiEjd-NrKyqzR2n8UUPz9ByWR7eOsYTwflsDau-5_c-X7yVoc1GaeSkosaDe8Zrm6y44T7qxhDq3S9X67GkNqn53qY2LTXJliHOZOV5LLomkT6L8shDz2nQPUx3NhS1y-7IprFFjHoGf8IjjD2A

{
  "titulo": "cita de barba azul aaaaaaaaaaa",
  "descripcion": "pasar una foto de la mama de pepe7"
}


### ==========================================
### 4. VER TODAS LAS CITAS
### ==========================================
GET http://127.0.0.1:8000/citas/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY3VhcnRvLXRyaW1lc3RyZS1jcmlzdGlhbiIsImF1ZCI6ImN1YXJ0by10cmltZXN0cmUtY3Jpc3RpYW4iLCJhdXRoX3RpbWUiOjE3NzU2NjcwMzMsInVzZXJfaWQiOiJ5dE1oUWl4cGpMUVBpZGlJbFprUXFoOEsxaG0xIiwic3ViIjoieXRNaFFpeHBqTFFQaWRpSWxaa1FxaDhLMWhtMSIsImlhdCI6MTc3NTY2NzAzMywiZXhwIjoxNzc1NjcwNjMzLCJlbWFpbCI6InBlcGU3QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJwZXBlN0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.DUBpBPa8Tk1_Ttmmd9r5ZhPud7aiYQweObSKAPxZatL5kXTiVZVfpy58YNzwA7A-3Z2WHXx5hQVz-rkkqDs6DbR7_43C_zpvU3WIj_e8P-2u-3poS0VfdUb0Yz7QAsHPtANO4Fkoyniu6sA1fTREf4bpNGgPyD5WL3j-_LaRAXVK952PfVP8wrE8IC-JFoywFtoPiEjd-NrKyqzR2n8UUPz9ByWR7eOsYTwflsDau-5_c-X7yVoc1GaeSkosaDe8Zrm6y44T7qxhDq3S9X67GkNqn53qY2LTXJliHOZOV5LLomkT6L8shDz2nQPUx3NhS1y-7IprFFjHoGf8IjjD2A


### ==========================================
### 5. EDITAR CITA
### ==========================================
PUT http://127.0.0.1:8000/citas/FniEAssHE3ResXk46IzL/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY3VhcnRvLXRyaW1lc3RyZS1jcmlzdGlhbiIsImF1ZCI6ImN1YXJ0by10cmltZXN0cmUtY3Jpc3RpYW4iLCJhdXRoX3RpbWUiOjE3NzU2NjcwMzMsInVzZXJfaWQiOiJ5dE1oUWl4cGpMUVBpZGlJbFprUXFoOEsxaG0xIiwic3ViIjoieXRNaFFpeHBqTFFQaWRpSWxaa1FxaDhLMWhtMSIsImlhdCI6MTc3NTY2NzAzMywiZXhwIjoxNzc1NjcwNjMzLCJlbWFpbCI6InBlcGU3QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJwZXBlN0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.DUBpBPa8Tk1_Ttmmd9r5ZhPud7aiYQweObSKAPxZatL5kXTiVZVfpy58YNzwA7A-3Z2WHXx5hQVz-rkkqDs6DbR7_43C_zpvU3WIj_e8P-2u-3poS0VfdUb0Yz7QAsHPtANO4Fkoyniu6sA1fTREf4bpNGgPyD5WL3j-_LaRAXVK952PfVP8wrE8IC-JFoywFtoPiEjd-NrKyqzR2n8UUPz9ByWR7eOsYTwflsDau-5_c-X7yVoc1GaeSkosaDe8Zrm6y44T7qxhDq3S9X67GkNqn53qY2LTXJliHOZOV5LLomkT6L8shDz2nQPUx3NhS1y-7IprFFjHoGf8IjjD2A

{
  "titulo": "cita de barba azul editada",
  "descripcion": "pasar una foto de la mama de pepe editada",
  "estado": "En Progreso"
}


### ==========================================
### 6. ELIMINAR CITA
### ==========================================
DELETE http://127.0.0.1:8000/citas/1WjZOF0mBeiTXvezj7yg/delete/ 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlODJhZmI0ZWY2OWI3NjM4MzA2OWFjNmI1N2U3ZTY1MjAzYmZlOTYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vY3VhcnRvLXRyaW1lc3RyZS1jcmlzdGlhbiIsImF1ZCI6ImN1YXJ0by10cmltZXN0cmUtY3Jpc3RpYW4iLCJhdXRoX3RpbWUiOjE3NzU2NjcwMzMsInVzZXJfaWQiOiJ5dE1oUWl4cGpMUVBpZGlJbFprUXFoOEsxaG0xIiwic3ViIjoieXRNaFFpeHBqTFFQaWRpSWxaa1FxaDhLMWhtMSIsImlhdCI6MTc3NTY2NzAzMywiZXhwIjoxNzc1NjcwNjMzLCJlbWFpbCI6InBlcGU3QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJwZXBlN0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.DUBpBPa8Tk1_Ttmmd9r5ZhPud7aiYQweObSKAPxZatL5kXTiVZVfpy58YNzwA7A-3Z2WHXx5hQVz-rkkqDs6DbR7_43C_zpvU3WIj_e8P-2u-3poS0VfdUb0Yz7QAsHPtANO4Fkoyniu6sA1fTREf4bpNGgPyD5WL3j-_LaRAXVK952PfVP8wrE8IC-JFoywFtoPiEjd-NrKyqzR2n8UUPz9ByWR7eOsYTwflsDau-5_c-X7yVoc1GaeSkosaDe8Zrm6y44T7qxhDq3S9X67GkNqn53qY2LTXJliHOZOV5LLomkT6L8shDz2nQPUx3NhS1y-7IprFFjHoGf8IjjD2A