"""
Django settings for firebase project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================
# Seguridad básica
# =========================
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-b01%)(06ar+%i#wam)hjct3_81&xp!1j0vu%+2rpc^g0#c2k!1")
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"
ALLOWED_HOSTS = ["*"]  # en producción especifica tu dominio/IP

# =========================
# Aplicaciones instaladas
# =========================
INSTALLED_APPS = [
    'daphne',
    'channels',   # 🔹 necesario para WebSockets
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',   # tu app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'firebase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'firebase.wsgi.application'
ASGI_APPLICATION = 'firebase.asgi.application'  # 🔹 importante para Channels

# =========================
# Base de datos
# =========================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# =========================
# Validación de contraseñas
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =========================
# Internacionalización
# =========================
LANGUAGE_CODE = 'es'  # 🔹 idioma español
TIME_ZONE = 'America/Bogota'  # 🔹 zona horaria Colombia
USE_I18N = True
USE_TZ = True

# =========================
# Archivos estáticos
# =========================
STATIC_URL = 'static/'

# =========================
# Django REST Framework
# =========================
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# =========================
# DRF Spectacular (Swagger)
# =========================
SPECTACULAR_SETTINGS = {
    'TITLE': 'API de citas',
    'DESCRIPTION': 'API para gestión de citas con Firebase Authentication y roles',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# =========================
# Channels (WebSockets)
# =========================
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"  # 🔹 desarrollo
        # En producción usa Redis:
        # "BACKEND": "channels_redis.core.RedisChannelLayer",
        # "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

# =========================
# Primary Key por defecto
# =========================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
